### ISSUE TITLE
File Size Balloons and PDF gets Corrupted

### ISSUE THREAD

**Issue by nbyloff** [ajaxray/php-watermark#10]
In testing, this package has been working flawlessly. However, I got the final document we're going to use live. For some reason, that document doesn't work.

The original PDF is 853KB. However when I try and watermark it with my name and email, it blows up to like 20MB in size, and the outputted file is corrupted and can't be open. Please note, nothing about this code changes except pointing to a different PDF.

````
$documentPath = BEDROCK_CONFIG_DIR . '/1519939315.XeevRAl27BGXn9MAVctvCYBATWxL88sKm04YU1e5.pdf';
      $inputFile = '1519939315.XeevRAl27BGXn9MAVctvCYBATWxL88sKm04YU1e5.pdf';
      $watermark = new Watermark(BEDROCK_CONFIG_DIR . '/1519939315.XeevRAl27BGXn9MAVctvCYBATWxL88sKm04YU1e5.pdf');

      // set watermark text
      $text = $row->first_name . " " . $row->last_name . " \r\n " . $row->email;

      // Watermark with text
      $watermark->setFont('AvantGarde-BookOblique');
      $watermark->setFontSize(24);
      $watermark->setRotate(345);
      $watermark->setOffset(0, 0);
      $watermark->setOpacity(.2);
      $watermark->setPosition(Watermark::POSITION_CENTER);

      // write file to hd
      $outputFile = BEDROCK_CONFIG_DIR . '/output/' . $inputFile;
      $watermark->withText($text, $outputFile);
````

I am not getting any errors in the console other than it takes a long time obviously. Is there any specific way I need to save PDFs, or format them in a specific way? 

EDIT: The PDFs are just word documents I click save as PDF or print to PDF. The latest test I did this way created a PDF 2MB. When I ran the above script over it, the output was 13MB (Only putting my name & email as you can see). 

In this last example, it opened OK, but why did adding my name & email to each page (81 pages), increase the size by 11MB?

**Comment by nbyloff** [comment]
I thought ghostscript was run automatically. I just ran it against my file, and reduced it from 13MB to 6.3MB. Is going from less than 1MB to 6MB a reasonable expectation for my use case? Or is there further PDF compression that can happen?

````
gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile=output.pdf input.pdf
````

**Comment by ajaxray** [comment]
Actually, when using the imagemagick + ghostscript extraction and joining pdf pages, it has a few drawbacks including file-size issue.
So, I am planning to write a cli tool for PDF watermarking that will work without converting pages into images. Will update here soon.

**Comment by nbyloff** [comment]
Great to hear; this package works flawlessly. Let me know if I can help

**Comment by nbyloff** [comment]
Probably shouldn't have closed this until you are ready to do an update.

**Comment by aftab-currency** [comment]
I m facing the very same problem, 1.6 MB pdf file increased to 30MB. Any update on the issue?

**Comment by ajaxray** [comment]
Not yet, sorry :( 
Trying to release [the committed tool](https://github.com/ajaxray/php-watermark/issues/10#issuecomment-399630264) very soon...

**Comment by ajaxray** [comment]
> I m facing the very same problem, 1.6 MB pdf file increased to 30MB. Any update on the issue?

Not yet, sorry :( 
Trying to release [the committed tool](https://github.com/ajaxray/php-watermark/issues/10#issuecomment-399630264) very soon...

**Comment by ajaxray** [comment]
UPDATE: The alternative tool is ready :)
Will release and share here withing this weekend (InshaAllah).

**Comment by nssmart** [comment]
Thank you!
We here are also looking very much forward for this release!

**Comment by ajaxray** [comment]
I've released the initial version of the command line tool for PDF watermarking. 
https://github.com/ajaxray/markpdf

Please download, check and let me know your feedback.
