### ISSUE TITLE
mistake in readme

### ISSUE THREAD

**Issue by metaer** [ajaxray/php-watermark#13]
setRotate, but not setRotation:
![cd753b91ff](https://user-images.githubusercontent.com/6103208/49309334-f59d0380-f4eb-11e8-8198-32ac43867a4a.png)

**Comment by ajaxray** [comment]
Thanks a lot for mentioning! 👍 
Fixed it.

**Comment by jigo3068** [comment]
Hi friend

I have used your library for pdf watermark and it would be working well but pdf quality is distorted, can you please guide mw how to make it same as original with watermark

Thanks!
Jigs
