### ISSUE TITLE
File resolution very small after add watermark

### ISSUE THREAD

**Issue by kimhoun** [ajaxray/php-watermark#18]
What is the problem when i try to add watermark to my PDF file and it turn to very bad resolution?

**Comment by ajaxray** [comment]
There is some known issues related to PDF watermarking. Please [see here](https://github.com/ajaxray/php-watermark#important-update-for-pdf-watermarking).

You may use https://github.com/ajaxray/markpdf for a significantly better results with PDF watermarking.
