### ISSUE TITLE
generate pdf with images lead the pdf file indistinct

### ISSUE THREAD

**Issue by ProgrammerBill** [ajaxray/php-watermark#2]
Hi ! I have tried to generate a Pdf file with Image ,but the contents of the pdf become indistinct.Is it possible to make it clear as the original one?

**Comment by ajaxray** [comment]
Hello @ProgrammerBill ,
As per current implementation, it's not possible.
But, don't worry, there have some other PDF library in PHP which can do this.
For example, check this example with fpdf - http://www.fpdf.org/en/script/script9.php
