### ISSUE TITLE
getTextMarkCommand not support for the French language

### ISSUE THREAD

**Issue by purohitvijay** [ajaxray/php-watermark#20]
Hi Anis Uddin Ahmad,

I'm using text like "Approuvé, Non Publié" and it has been converting text like "Approuv, Non Publi" as a watermark. This removing "é" from the original text.

Thank You in Advance.

**Comment by purohitvijay** [comment]
Hi @ajaxray,

Any update on this issue.

Thank You

**Comment by ajaxray** [comment]
Hello @purohitvijay ,

I was able to watermark with your provided text, (with Arial Unicode font) without any change. :)

See example (your text on an FCK Editor screenshot): 
![result_simple_french](https://user-images.githubusercontent.com/439612/71590410-82cce480-2b52-11ea-94c0-f7b960f581cb.jpg)

Please check if your locale is set properly.
You may try `setlocale(LC_CTYPE, "en_US.UTF-8");` at the beginning of
 file where you are doing th watermarking.

**Comment by purohitvijay** [comment]
Thank You so much it's working.
