### ISSUE TITLE
Help with basic installation

### ISSUE THREAD

**Issue by makemagik** [ajaxray/php-watermark#21]
Hi,

I'm using the script without composer. I downloaded the archive and tried to run the example_img.php.

I had to change the `include 'vendor/autoload.php';` since there's no autoload.php file (I suppose this come from Composer)

I used the following include : 

`include '../src/Ajaxray/PHPWatermark/Watermark.php';`

I get the following error: 

`Uncaught Error: Class 'Ajaxray\PHPWatermark\CommandBuilders\ImageCommandBuilder' not found in /src/Ajaxray/PHPWatermark/Watermark.php:112`

Any ideas on what I'm doing wrong? I have not modified any other files.

Thanks!

**Comment by makemagik** [comment]
I figured that we need to include all the PHP files directly and it works like a charm :)

```
require_once('../src/Ajaxray/PHPWatermark/Watermark.php');
require_once('../src/Ajaxray/PHPWatermark/CommandBuilders/AbstractCommandBuilder.php');
require_once('../src/Ajaxray/PHPWatermark/CommandBuilders/ImageCommandBuilder.php');
require_once('../src/Ajaxray/PHPWatermark/CommandBuilders/PDFCommandBuilder.php');
require_once('../src/Ajaxray/PHPWatermark/Requirements/RequirementsChecker.php');
```

**Comment by ajaxray** [comment]
Hello @makemagik ,

Sorry for late reply.
Glad to know that you've solved it 👍 

You could also try with `composer dump-autoload -o` for generating optimized autoload file.

**Comment by kangsuha** [comment]
Hi Ajaxray,

I have tried your script, but when I run examples/example_pdf.php, it's only a blank page and no result anything in the directory. What must I do?

Thanks
