### ISSUE TITLE
not support php 7.3

### ISSUE THREAD

**Issue by mynameispond** [ajaxray/php-watermark#23]
Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in src\Ajaxray\PHPWatermark\Watermark.php on line 31

**Comment by ajaxray** [comment]
Hi @duckfeels ,
Thanks a lot for asking.

As mentioned in README, the latest master is not supported for < PHP 8.
For PHP versions `>= 5.6` to `<8` please use `v0.1.2`.

Please check [installation](https://github.com/ajaxray/php-watermark#installation) section for details.
