### ISSUE TITLE
Cant see Ajaxarray namespace

### ISSUE THREAD

**Issue by klim2020** [ajaxray/php-watermark#24]
Cant see Ajaxarray namespace

**Comment by klim2020** [comment]
I use composer install to add watermark library in my project, after that I cant use new Ajaxarray/PHPWatermark/Watermark() in my project

**Comment by ajaxray** [comment]
Hi @klim2020 ,

Thanks a lot for asking. ❤️

I have just tested with PHP interactive shell and it was found working as expected.

Here is what I did step by step:
1. Installed php-watermark with composer
2. Entered into PHP interactive shell.
3. Included  `vendor/autoload.php` file
4. Tried to create an instance of `Ajaxarray/PHPWatermark/Watermark()` with an imaginary file name.
5. It throws exception and says the file was not found - which indicates the class was loaded properly.

The Screenshot of the above steps:
![CleanShot 2021-10-04 at 23 48 21@2x](https://user-images.githubusercontent.com/439612/135899416-c1719304-cddd-47c9-99bf-a7cf084ca074.png)
Note: My PHP version is `8.0.2`

Can you please check your autoload file is loaded properly?
