### ISSUE TITLE
Png watermark transparency.

### ISSUE THREAD

**Issue by spuki** [ajaxray/php-watermark#5]
I have a trouble which described here
http://www.imagemagick.org/discourse-server/viewtopic.php?t=31549
When I use a png image as a watermark I get gray background as a result.
So I propose to make changes in the method getMarkerOpacity of class PDFCommandBuilder:
replace strings

$opacity = $this->getOpacity() * 100;
return "-alpha set -channel A -evaluate set {$opacity}%";

with strings

$opacity = $this->getOpacity();
return "-alpha set -channel A -evaluate multiply {$opacity}";

**Comment by ajaxray** [comment]
Thanks a lot for informing ❤️. 
I have tested with PHP official png logo using `ImageMagick 7.0.7-25 Q16 x86_64`. But could not re-generate the issue. The transparent portion of PNG was fully transparent as expected.

Can you please mention the ImageMagick version. A sample PNG that caused the issue will be more helpful.

**Comment by ajaxray** [comment]
Hello @spuki ,
It's been years since we've discussed on the issue.
Seems you're no more facing this issue or you don't need this resolved anymore.
So, I closing this issue now. Please re-open if you still have this issue.

Thanks.
