### ISSUE TITLE
can I tile rotated transpared watermark logo (image not text)?

### ISSUE THREAD

**Issue by VictorZamoulko** [ajaxray/php-watermark#8]
list($width, $height) = getimagesize($this->inputSrcWM);
$watermark->setTileSize($width * $this->tile_ratio, $height * $this->tile_ratio);

looks like do not work for image logo source.

**Comment by ajaxray** [comment]
Sorry to say, so far rotation is not supported for image watermark.
You may check other limitations in [support matrix table](https://github.com/ajaxray/php-watermark#customization-options).
